# Generated by Django 4.2.9 on 2024-02-01 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': '관념',
            },
        ),
        migrations.AddField(
            model_name='picture',
            name='mind',
            field=models.ManyToManyField(blank=True, related_name='mind', to='pictures.mind'),
        ),
    ]
