# Generated by Django 4.2.9 on 2024-02-01 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0002_mind_picture_mind'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mind',
            options={'verbose_name': 'mind'},
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='mind',
            new_name='마음',
        ),
    ]
