# Generated by Django 4.2.9 on 2024-02-01 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0003_alter_mind_options_rename_mind_picture_마음'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mind',
            options={},
        ),
        migrations.AlterModelTable(
            name='mind',
            table='mind',
        ),
    ]
