# Generated by Django 4.2.9 on 2024-02-18 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0006_remove_mind_created_remove_mind_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'color',
            },
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'shape',
            },
        ),
        migrations.AddField(
            model_name='picture',
            name='색깔',
            field=models.ManyToManyField(blank=True, null=True, related_name='colors', to='pictures.color'),
        ),
        migrations.AddField(
            model_name='picture',
            name='형태',
            field=models.ManyToManyField(blank=True, null=True, related_name='shapes', to='pictures.shape'),
        ),
    ]
