# Generated by Django 4.2.9 on 2024-02-19 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0007_color_shape_picture_색깔_picture_형태'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='color',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='색깔',
            new_name='색',
        ),
    ]
