# Generated by Django 4.2.9 on 2024-02-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0009_picture_구매자_picture_번호_picture_보관위치_picture_상세설명_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
