# Generated by Django 4.2.9 on 2024-02-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0010_alter_picture_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
