# Generated by Django 4.2.9 on 2024-02-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0011_alter_picture_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='마음',
            field=models.ManyToManyField(blank=True, related_name='pictures', to='pictures.mind'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='번호',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='picture',
            name='상세설명',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='picture',
            name='색',
            field=models.ManyToManyField(blank=True, related_name='pictures', to='pictures.color'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='연속번호',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='picture',
            name='이미지',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='picture',
            name='일차',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='picture',
            name='작품번호',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='picture',
            name='창작날짜',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='picture',
            name='형태',
            field=models.ManyToManyField(blank=True, related_name='pictures', to='pictures.shape'),
        ),
    ]
